version: '2.3'

services:
  main:
    container_name: FSRT
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ipc: "host"
    env_file:
      - "docker-compose-env/main.env"
    volumes:
      - type: volume
        source: nfs_shared_
        target: /nfs_shared_
        volume:
          nocopy: true
      - "/home/mmlab/Documents/diffusion/nlp/diffusers:/user"
    expose:
      - "8000"
    ports:
      - "28100:8000"
      - "20122:22"
      - "26106:6006"
      - "28188:8888"
    stdin_open: true
    tty: true
    runtime: nvidia  # Add this line to specify the NVIDIA runtime
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm

volumes:
  nfs_shared_:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume3/nfs_shared_"
